### ISSUE TITLE
Fix layout of papers cards on "papers/index.html"

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#10]
At smaller sizes, strange wrapping occurs on the header text of unexpanded cards.

**Comment by dwtj** [comment]
Jackson, is this issue ready to be closed as of commit 2f4007b?

**Comment by jlmaddox** [comment]
I don't believe I had padding on the card block because the animation couldn't handle it. Opening/closing the accordions is "jerky", so I'll look into that. The layout is fine, however.

**Comment by jlmaddox** [comment]
The animation should be fixed now. I think this can be closed.
