### ISSUE TITLE
Add a table of contents to the "projects.html" page

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#12]

**Comment by nate-wernimont** [comment]
Professor Rajan would also like the table of contents on the projects page to have no prefix on the top level and the second level be converted to bullet points. Might have to find a plugin or do it by hand. I think that is out of the scope of {:toc}

**Comment by dwtj** [comment]
My first impression is that you are probably right that this customization can't be done by configuring `{:toc}`. Rather, we'll want to do it via the CSS which is styling this particular table of contents on this particular page.

We haven't really explicitly settled on per-page CSS practices. (Can we add CSS file links or embedded styles into individual markdown pages?)

I think our current practice is to just have global CSS and if we just want it to just work on one page then we add HTML element with an ID that we only expect to show up on that one page. We then add styling to the global styling rules that selects that ID.

So, I propose:

-   Wrap this `{:toc}` in a `<div id="papers-markdown-toc">`.
-   Add a CSS rule to select and style the first level.
-   Add a CSS rule to select and style the deeper levels.

Note you will want to use [this CSS selector](https://www.w3schools.com/cssref/sel_element_gt.asp) to help differentiate between the levels.

Also, if you're confused about how the styling files work, note that we're using [SCSS](http://sass-lang.com/guide), which slightly extends CSS. (I don't think we're really using many features except for rule nesting and file importing.) As part of the build, the SCSS is automatically compiled to CSS.

**Comment by nate-wernimont** [comment]
As an update, adding styles into individual markdown pages works fine. You just wrap the CSS in <style></style> in the markdown doc, and it works fine as well. With my commit, I left it as global CSS with an ID, though, in order to maintain a uniform style. Thank you for the advice as well.
