### ISSUE TITLE
Add warning for incorrectly formatted `extra_download_links`

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#16]
As of commit e7a279c, each of a paper's `extra_download_links`  are expected to be an object literal with two properties, `link` and `title`. We should add a check to `warnings.html` to help ensure that any extra download link has both of these properties.

**Comment by jlmaddox** [comment]
Should be done as of commit bc58805.

**Comment by dwtj** [comment]
Looks good to me. Thanks, @jlmaddox. Closing.
