### ISSUE TITLE
Fix all current warnings

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#18]

**Comment by nate-wernimont** [comment]
All warnings have been currently fixed except for paper CCSC-10 that needs an abstract. This can't be done because the paper doesn't have one.

**Comment by jlmaddox** [comment]
I looked on ACM for this paper, and found [this](https://dl.acm.org/citation.cfm?id=1747190). It looks like they used the first paragraph as the abstract, so we could probably do the same.
