### ISSUE TITLE
Add list of recent news items to the home page

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#22]
This replaces Issue #7.

**Comment by dwtj** [comment]
@jlmaddox As of commit dac14a0e, how does this look to you?

**Comment by jlmaddox** [comment]
This is also a response to issue #21:

Looks pretty good, and I don't have many complaints. In regards to news specifically, though, perhaps we should simply not have the card link to anything if there is no body to the news. Similarly on the news page. It's odd to click the link and be taken to a page with a title and nothing else. At the same time it could be confusing if only some of them can be clicked unless there's a visual indicator of some sort.

It also seems like the font sizes of the news and highlighted papers differ. It gives it a weird effect when looking at them side by side. I think it'd be better if they had the same font size.

**Comment by dwtj** [comment]
Ok. I'll make the font sizes the same. (My thinking was that we want to highlight papers a bit more than news, but I see your point.)

Regarding your first point, please make a separate issue for this. Thanks.
