### ISSUE TITLE
Upload built site to `pyrite.cs.iastate.edu`

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#23]

**Comment by dwtj** [comment]
A first version of the new site has been deployed.

Commit 53045da adds a deploy script to help do this again with future site updates.

**Comment by ddmills** [comment]
About time you got this deployed! i was dying to see it. Looks good, congrats!

**Comment by dwtj** [comment]
Wow. Thanks, Dalton.

You know, we'd love to hear if you have any advice for how to improve the site. Our currently planned next step is to adjust the layout and styling to look more like https://las.iastate.edu
