### ISSUE TITLE
Compile bib entries to a more human-readable format

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#28]
Last week Dr. Rajan requested this feature by email. As he pointed out, a quick Google search indicates that there are a number of Jekyll plugins out there that should allow us to easily add this feature.

**Comment by dwtj** [comment]
To be clear, we want papers pages to include both biblatex entries and their compiled form.

**Comment by nate-wernimont** [comment]
What kind of compiled form should they be? APA? MLA?

**Comment by dwtj** [comment]
ACM is what we were looking for.
