### ISSUE TITLE
Add homepage carousel of images

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#6]

**Comment by dwtj** [comment]
I took a first stab at this with commit a3c4b87. Unfortunately, the left-right arrows do not seem to be showing up. Not sure why yet.

![screen shot 2017-01-14 at 4 33 30 pm](https://cloud.githubusercontent.com/assets/2457848/21958589/475e1e66-da77-11e6-8b26-b25db925439a.png)

**Comment by jlmaddox** [comment]
Looks like we may have to update bootstrap actually. I ctrl+f'd "carousel-control-next" in the current bootstrap css and came up blank. However, it does appear in the css for bootstrap alpha 6.

**Comment by dwtj** [comment]
I was actually wondering if that was the case. Thanks for finding out for sure.

Note that the reason that I got it wrong was that I was working from an example in the Bootstrap Alpha 6 docs. We ought to expect to see more such errors moving forward.

This begs the question: is the upgrade worth it? From their blog post, Alpha 6 looks like a big change. Or should we just stick with the plan and wait until the first Beta?

If we aren't going to change to Alpha 6, I suggest that we not worry about the left-right arrows for now but comment them out the relevant HTML until we do the Bootstrap upgrade.

**Comment by jlmaddox** [comment]
I'm not really sure which way would be better to go with. Either case may or may not be worse than the other depending on how many changes are between v6 and the beta. If we want to deliver this quickly, then it's probably best to drop the arrows for now, though, and update to the beta when it comes out later.

**Comment by dwtj** [comment]
Carousel left/right controls will be re-enabled later as part of Issue #20.

The carousel undoubtedly deserves more work. (In particular, it needs more and better "ads".) But this is good enough for our first deliverable. Improvements can be attached to subsequent issues.

Closing this issue as of 78856c1.
