### ISSUE TITLE
Prevent header text wrap at "xs" size

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#9]
See "Laboratory for Software Design" at bootstrap's extra small size.

Idea: Fix this by making this text smaller when "xs" is enabled.

**Comment by dwtj** [comment]
As you can see in the screen capture below, wrapping still occurs on my system at the site's minimum width of 320px. This happens on my particular system, but it may be a consequence of the particular font that I am using (or even something more browser specific).

![screen shot 2017-01-14 at 4 26 26 pm](https://cloud.githubusercontent.com/assets/2457848/21958563/8fc55684-da76-11e6-95cb-519467607050.png)

320px was chosen after some brief Googling indicated (at least to me) that 320px may be a common min-width target for responsive sites. (IDK, are common modern mobile devices this small?)

**Comment by jlmaddox** [comment]
I suppose the font size could be changed back to 1.15rem and I can add that separate xs span with a smaller size of 0.9rem or something. It's hard to say how small exactly it needs to be though because of browser/system differences.

**Comment by dwtj** [comment]
Ok. I'll leave it up to you.

**Comment by jlmaddox** [comment]
Decided on 1rem instead of 0.9rem in commit 6e82c2d. Will need you to verify there's no wrapping on your end.

**Comment by dwtj** [comment]
I checked it on my system, and it looks good. Thanks. Closing.
